version: "3.8"

services:
  postgres:
    image: postgis/postgis:14-3.2
    environment:
      POSTGRES_DB: provisions_link
      POSTGRES_USER: provisions_user
      POSTGRES_PASSWORD: provisions_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
