# Generated by Django 5.0 on 2025-10-22 01:25

import apps.vendors.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, help_text='Vendor logo', null=True, upload_to=apps.vendors.models.vendor_logo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
