# Generated by Django 5.0 on 2025-09-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID', max_length=200, null=True),
        ),
    ]
