# Generated by Django 5.0 on 2025-11-03

from django.db import migrations, models


def fix_empty_payment_intent_ids(apps, schema_editor):
    """Convert empty strings to NULL for existing orders."""
    Order = apps.get_model('orders', 'Order')

    # Update all empty strings to None
    updated = Order.objects.filter(
        stripe_payment_intent_id=''
    ).update(
        stripe_payment_intent_id=None
    )

    if updated:
        print(f"✅ Fixed {updated} orders with empty payment intent IDs")


def reverse_fix(apps, schema_editor):
    """Reverse migration - convert NULL back to empty string."""
    Order = apps.get_model('orders', 'Order')

    updated = Order.objects.filter(
        stripe_payment_intent_id__isnull=True
    ).update(
        stripe_payment_intent_id=''
    )

    if updated:
        print(f"Reverted {updated} orders to empty strings")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [

        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Stripe payment intent ID',
                max_length=200,
                null=True
            ),
        ),


        migrations.RunPython(fix_empty_payment_intent_ids, reverse_fix),
    ]
