# Generated by Django 5.0 on 2025-11-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_fix_order_payment_intents'),
        ('buying_groups', '0009_make_delivery_address_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='group_commitment',
            field=models.ForeignKey(
                blank=True,
                help_text='Group commitment that created this order item (if applicable)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='order_items',
                to='buying_groups.groupcommitment'
            ),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['group_commitment'], name='order_items_group_c_idx'),
        ),
    ]
