# Generated by Django 5.0 on 2025-09-24 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buying_groups', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinggroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_groups', to='products.product'),
        ),
        migrations.AddField(
            model_name='groupcommitment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_commitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcommitment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='buying_groups.buyinggroup'),
        ),
        migrations.AddField(
            model_name='groupupdate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='buying_groups.buyinggroup'),
        ),
        migrations.AddIndex(
            model_name='buyinggroup',
            index=models.Index(fields=['status', 'expires_at'], name='buying_grou_status_108bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='buyinggroup',
            index=models.Index(fields=['product', 'status'], name='buying_grou_product_d00ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='buyinggroup',
            index=models.Index(fields=['created_at'], name='buying_grou_created_787824_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcommitment',
            index=models.Index(fields=['group', 'status'], name='group_commi_group_i_f9b27c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcommitment',
            index=models.Index(fields=['buyer', 'status'], name='group_commi_buyer_i_ace587_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcommitment',
            index=models.Index(fields=['committed_at'], name='group_commi_committ_57f3b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupcommitment',
            unique_together={('group', 'buyer')},
        ),
        migrations.AddIndex(
            model_name='groupupdate',
            index=models.Index(fields=['group', 'created_at'], name='group_updat_group_i_839402_idx'),
        ),
        migrations.AddIndex(
            model_name='groupupdate',
            index=models.Index(fields=['event_type'], name='group_updat_event_t_5a67ea_idx'),
        ),
    ]
