# Generated by Django 5.0 on 2025-10-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying_groups', '0002_initial'),
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcommitment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order created from this commitment when group succeeds', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_commitment', to='orders.order'),
        ),
    ]
