# Generated by Django 5.0 on 2025-10-20 23:59

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('buying_groups', '0003_groupcommitment_order'),
    ]

    operations = [
        # Step 1: Remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name='groupcommitment',
            unique_together=set(),
        ),

        # Step 2: Add new partial unique constraint
        # Only ONE pending/confirmed commitment per (group, buyer)
        # But multiple cancelled commitments are allowed
        migrations.AddConstraint(
            model_name='groupcommitment',
            constraint=models.UniqueConstraint(
                fields=['group', 'buyer'],
                condition=Q(status__in=['pending', 'confirmed']),
                name='unique_active_commitment_per_buyer'
            ),
        ),
    ]
