# Generated by Django 5.0 on 2025-10-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buying_groups', '0004_fix_commitment_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupcommitment',
            name='unique_active_commitment_per_buyer',
        ),
    ]
