# Generated by Django 5.0 on 2025-11-03 00:34

from django.db import migrations, models


def fix_empty_payment_intent_ids(apps, schema_editor):
    """Convert empty strings to NULL for existing commitments."""
    GroupCommitment = apps.get_model('buying_groups', 'GroupCommitment')

    # Update all empty strings to None
    updated = GroupCommitment.objects.filter(
        stripe_payment_intent_id=''
    ).update(
        stripe_payment_intent_id=None
    )

    if updated:
        print(f"✅ Fixed {updated} commitments with empty payment intent IDs")


def reverse_fix(apps, schema_editor):
    """Reverse migration - convert NULL back to empty string."""
    GroupCommitment = apps.get_model('buying_groups', 'GroupCommitment')

    updated = GroupCommitment.objects.filter(
        stripe_payment_intent_id__isnull=True
    ).update(
        stripe_payment_intent_id=''
    )

    if updated:
        print(f"Reverted {updated} commitments to empty strings")


class Migration(migrations.Migration):

    dependencies = [
        ('buying_groups', '0005_remove_groupcommitment_unique_active_commitment_per_buyer'),
    ]

    operations = [

        migrations.AlterField(
            model_name='groupcommitment',
            name='stripe_payment_intent_id',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Stripe payment intent for pre-authorization',
                max_length=200,
                null=True  # Remove the NOT NULL constraint
            ),
        ),


        migrations.RunPython(fix_empty_payment_intent_ids, reverse_fix),
    ]
