# Generated by Django 5.0 on 2025-11-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying_groups', '0006_fix_empty_payment_intents'),
        ('core', '0004_remove_address_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcommitment',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Delivery address for this commitment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_commitments', to='core.address'),
        ),
        migrations.AddField(
            model_name='groupcommitment',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', help_text='Optional delivery notes'),
        ),
    ]
