# Generated by Django 5.0 on 2025-11-08

from django.db import migrations


def backfill_commitment_addresses(apps, schema_editor):
    """Fill in missing addresses for old commitments"""
    GroupCommitment = apps.get_model('buying_groups', 'GroupCommitment')
    Address = apps.get_model('core', 'Address')

    # Find all commitments without an address
    commitments_without_address = GroupCommitment.objects.filter(
        delivery_address__isnull=True)
    total = commitments_without_address.count()

    print(f"\n🔄 Filling in addresses for {total} old commitments...")

    success = 0
    failed = 0

    for commitment in commitments_without_address:
        # Try to find the buyer's default address
        buyer_address = Address.objects.filter(
            user=commitment.buyer,
            is_default=True
        ).first()

        # If no default, use any address they have
        if not buyer_address:
            buyer_address = Address.objects.filter(
                user=commitment.buyer
            ).first()

        if buyer_address:
            # Save the address to this commitment
            commitment.delivery_address = buyer_address
            commitment.save(update_fields=['delivery_address'])
            success += 1
            print(
                f"  ✓ Commitment {commitment.id} -> Address {buyer_address.id}")
        else:
            # This buyer has no addresses at all
            failed += 1
            print(f"  ✗ Commitment {commitment.id} - Buyer has no addresses!")

    print(f"\n✅ Done: {success} successful, {failed} failed")


def reverse_backfill(apps, schema_editor):
    """If we need to undo this, set all addresses back to null"""
    GroupCommitment = apps.get_model('buying_groups', 'GroupCommitment')
    GroupCommitment.objects.all().update(delivery_address=None)


class Migration(migrations.Migration):

    dependencies = [
        ('buying_groups', '0007_groupcommitment_delivery_address_and_more'),
        ('core', '0004_remove_address_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(backfill_commitment_addresses, reverse_backfill),
    ]
