# Generated by Django 5.0 on 2025-11-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buying_groups', '0008_backfill_legacy_commitment_addresses'),
        ('core', '0004_remove_address_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcommitment',
            name='delivery_address',
            field=models.ForeignKey(
                help_text='Delivery address for this commitment',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='group_commitments',
                to='core.address',
                # No more null=True! Field is now required
            ),
        ),
    ]
