# Generated by Django 5.0 on 2025-10-22 01:25

import apps.products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Primary product image', null=True, upload_to=apps.products.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
